import = ["~/.config/alacritty/dracula.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 12.0

[font.bold]
family = "Fira Code"
style = "Bold"

[font.bold_italic]
family = "Fira Code"
style = "Bold Italic"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Regular"

[scrolling]
history = 0

[window]
decorations = "full"
dynamic_title = false
startup_mode = "Windowed"
title = "Alacritty"

[window.dimensions]
columns = 125
lines = 42
