#!/bin/sh
# This hook is run after every virtualenv is activated.
function _refresh_ps1() {
    ENV_PS1='(`basename $VIRTUAL_ENV` - `__git_ps1 "%s"`) '
    PS1=$ENV_PS1$_OLD_VIRTUAL_PS1
}

_refresh_ps1
